name: samui_quest
description: "Samui Quest - GPS Adventure Game"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.1.7

  cupertino_icons: ^1.0.8
  confetti: ^0.7.0
  
  # 🗺 Map
  latlong2: ^0.9.1
  mapbox_maps_flutter: ^2.6.0

  # 📍 GPS
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  flutter_compass: ^0.8.0

  # 🧠 State management
  provider: ^6.1.5+1

  # Audio
  audioplayers: ^6.0.0

  # 🎮 Game engine
  flame: ^1.14.0
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.1.3
  logger: ^2.7.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/seedscape_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/samui1.jpeg
    - assets/samui2.jpeg
    - assets/seedscape2.png
    - assets/seedscape1.png
    - assets/grass.png
    - assets/maps/
    - assets/icon/app_icon.png
    - assets/icon/seedscape_icon.png
    - assets/monkey_player.png
    - assets/elephant_player.png
    - assets/frog_player.png
    - assets/bird_player.png
    - assets/turtle_player.png
    - assets/audio/jungle.mp3
    - assets/audio/background2.mp3
    - assets/audio/walking.mp3
    - assets/audio/collect_so.mp3
    - assets/audio/dig_dirt.mp3
    - assets/audio/harvest.mp3
    - assets/audio/new_object_unlocked.mp3
    - assets/audio/new_badge.mp3
    - assets/animals/icons_300/
    - assets/animals/master/
    - assets/seeds/icons_300/
    - assets/seeds/master/
    - assets/fruits/icons_300/
    - assets/fruits/master/
    - assets/maps/colscreen.png
    - assets/marker.png
    - assets/quest_red.png
    - assets/quest_bronze.png
    - assets/quest_silver.png
    - assets/quest_gold.png
    - assets/fruitmarket.png
    - assets/animalmarket.png
    - assets/Catapult1.png
