// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Yf1b70ZI8IZztK1DZNkHb8ovag8z0zE',
    appId: '1:746034078897:web:6167da827dc12fc9482e90',
    messagingSenderId: '746034078897',
    projectId: 'seedscape26',
    authDomain: 'seedscape26.firebaseapp.com',
    storageBucket: 'seedscape26.firebasestorage.app',
    measurementId: 'G-W5V6KT3R6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh7UF5Fg3djyDISnOT-GUIRE2Z0b6SVbI',
    appId: '1:746034078897:android:45dd9a800bdd4883482e90',
    messagingSenderId: '746034078897',
    projectId: 'seedscape26',
    storageBucket: 'seedscape26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7RSqEVPGWAYEUQSEEQYE0nuMGxRD4Lvk',
    appId: '1:746034078897:ios:75550655656d783c482e90',
    messagingSenderId: '746034078897',
    projectId: 'seedscape26',
    storageBucket: 'seedscape26.firebasestorage.app',
    iosBundleId: 'com.example.samuiQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7RSqEVPGWAYEUQSEEQYE0nuMGxRD4Lvk',
    appId: '1:746034078897:ios:75550655656d783c482e90',
    messagingSenderId: '746034078897',
    projectId: 'seedscape26',
    storageBucket: 'seedscape26.firebasestorage.app',
    iosBundleId: 'com.example.samuiQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Yf1b70ZI8IZztK1DZNkHb8ovag8z0zE',
    appId: '1:746034078897:web:017aecc24649c022482e90',
    messagingSenderId: '746034078897',
    projectId: 'seedscape26',
    authDomain: 'seedscape26.firebaseapp.com',
    storageBucket: 'seedscape26.firebasestorage.app',
    measurementId: 'G-E5GFQ5M3MD',
  );
}
